#LOGIN
#============================
sonata_user_security:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_security_1.xml"

sonata_user_resetting:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_resetting_1.xml"
    prefix: /resetting

sonata_user_profile:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_profile_1.xml"
    prefix: /profile

sonata_user_register:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_registration_1.xml"
    prefix: /register

sonata_user_change_password:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_change_password_1.xml"
    prefix: /profile
sonata_user:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /admin
#hwi_oauth_redirect:
#   resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
#    prefix:   /connect
#hwi_oauth_login:
#    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
#    prefix:   /login
#facebook_login:
#    pattern: /login/check-facebook
#google_login:
#    pattern: /login/check-google

#SONATA ADMIN
#============================
admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
#APP
#============================
app:
    resource: @AppBundle/Controller/
    type:     annotation

homepage:
    defaults:  { _controller: AppBundle:Default:index}
    path: /


#POST
#============================
posts:
    defaults:  { _controller: AppBundle:Default:index}
    path: /news

#CHAPTER
#============================
chapters:
    defaults:  { _controller: AppBundle:Default:index}
    path: /chapters

#MANGAS
#============================
mangas:
    defaults:  { _controller: AppBundle:Default:index}
    path: /mangas

#CONTACT
#============================
contact:
    defaults:  { _controller: AppBundle:Default:index}
    path: /contact
