#LOGIN
#============================
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
#hwi_oauth_redirect:
#   resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
#    prefix:   /connect
#hwi_oauth_login:
#    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
#    prefix:   /login
#facebook_login:
#    pattern: /login/check-facebook
#google_login:
#    pattern: /login/check-google

#SONATA ADMIN
#============================
admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
#APP
#============================
app:
    resource: @AppBundle/Controller/
    type:     annotation

homepage:
    defaults:  { _controller: AppBundle:Default:index}
    path: /


#POST
#============================
posts:
    defaults:  { _controller: AppBundle:Default:index}
    path: /news

#CHAPTER
#============================
chapters:
    defaults:  { _controller: AppBundle:Default:index}
    path: /chapters

#MANGAS
#============================
mangas:
    defaults:  { _controller: AppBundle:Default:index}
    path: /mangas

#CONTACT
#============================
contact:
    defaults:  { _controller: AppBundle:Default:index}
    path: /contact
