sonata_news:
    title:        Glasisk-studio News
    link:         /
    description:  Add your for gladisk-studio
    salt:         'secureToken'
    permalink_generator:  sonata.news.permalink.collection #sonata.news.permalink.date

    comment:
        notification:
            emails:   [iskglad1@gmail.com, souleymane.gnandou@gmail.com]
            from:     comment@gladisk-studio.fr
            template: 'SonataNewsBundle:Mail:comment_notification.txt.twig'

#doctrine:
#   orm:
  #      entity_managers:
  #          default:
                #metadata_cache_driver: apc
                #query_cache_driver: apc
                #result_cache_driver: apc
  #              mappings:
  #                  ApplicationSonataNewsBundle: ~
  #                  SonataNewsBundle: ~